### ISSUE TITLE
Change to image aliases

### ISSUE THREAD

**Issue by evilsoapbox** [mbrukman/cloud-launcher#10]
Testing out the Cloudera steps today. Looks like image aliases have changed w/ gcloud. This is the error when creating the director VM (and specifying the use of CentOS6):

`WARNING: Image aliases are deprecated and will be removed in a future version. Please use --image-family=centos-6 and --image-project=centos-cloud instead.`

**Comment by mbrukman** [comment]
@evilsoapbox, thanks for catching and reporting this! I fixed all occurrences of the flag `--image` in the repo, both of which were in the Cloudera Director quickstart.
